// <auto-generated />
using System;
using Auth.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Auth.Data.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    partial class AuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("auth")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Auth.Authentication.Model.UserName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("SYSTEM");

                    b.Property<DateTime?>("CreateOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("LaboratoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Session")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SessionActiveOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("UserName", "auth");
                });

            modelBuilder.Entity("Auth.Authentication.Model.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("SYSTEM");

                    b.Property<DateTime?>("CreateOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("UserRole", "auth");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1b4dc80d-c3e8-4e6d-a9d6-2bbd478d2d00"),
                            CreateBy = "SYSTEM",
                            RoleCode = "00",
                            RoleDescription = "System administrator",
                            RoleName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("b89541a9-8ce6-4e95-820d-7c7785f96f01"),
                            CreateBy = "SYSTEM",
                            RoleCode = "01",
                            RoleDescription = "Department head",
                            RoleName = "DEPTHEAD"
                        },
                        new
                        {
                            Id = new Guid("52400f2b-0eaf-4921-9ad7-e527fb52bb02"),
                            CreateBy = "SYSTEM",
                            RoleCode = "02",
                            RoleDescription = "Lecturer",
                            RoleName = "LECTURER"
                        },
                        new
                        {
                            Id = new Guid("f801e95d-340b-4f34-8a6a-9deac4168003"),
                            CreateBy = "SYSTEM",
                            RoleCode = "03",
                            RoleDescription = "Student",
                            RoleName = "STUDENT"
                        });
                });

            modelBuilder.Entity("Auth.Authentication.Model.UserName", b =>
                {
                    b.HasOne("Auth.Authentication.Model.UserRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Auth_RoleId");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
