// <auto-generated />
using System;
using Asset.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Asset.Data.Migrations
{
    [DbContext(typeof(AssetDbContext))]
    [Migration("20260319143040_SetNullOnAssetUnitAssetDelete")]
    partial class SetNullOnAssetUnitAssetDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("asset")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Asset.Assets.Model.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AssetId");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("SYSTEM");

                    b.Property<DateTime?>("CreateOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LaboratoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LaboratoryId");

                    b.ToTable("Assets", "asset");
                });

            modelBuilder.Entity("Asset.Assets.Model.AssetUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AssetUnitId");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("SYSTEM");

                    b.Property<DateTime?>("CreateOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperationalStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SerialNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssetTag")
                        .IsUnique();

                    b.HasIndex("SerialNo")
                        .IsUnique();

                    b.ToTable("AssetUnits", "asset");
                });

            modelBuilder.Entity("Asset.Assets.Model.AssetUnitCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AssetUnitConditionId");

                    b.Property<Guid>("AssetUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("SYSTEM");

                    b.Property<DateTime?>("CreateOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEffectiveFromUnknown")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEffectiveToUnknown")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssetUnitId")
                        .IsUnique();

                    b.ToTable("AssetUnitConditions", "asset");
                });

            modelBuilder.Entity("Asset.Assets.Model.AssetUnitImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("AssetUnitImageId");

                    b.Property<Guid>("AssetUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("SYSTEM");

                    b.Property<DateTime?>("CreateOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssetUnitId");

                    b.ToTable("AssetUnitImages", "asset");
                });

            modelBuilder.Entity("Asset.Assets.Model.Laboratory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("LaboratoriesId");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("SYSTEM");

                    b.Property<DateTime?>("CreateOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("LaboratoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RoomNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Laboratories", "asset");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000101"),
                            CreateBy = "SYSTEM",
                            Description = "Primary lab for programming courses",
                            LaboratoryName = "CPE Programming Lab 1",
                            RoomNo = "G-601",
                            TeacherId = new Guid("00000000-0000-0000-0000-000000001001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000102"),
                            CreateBy = "SYSTEM",
                            Description = "Advanced programming and web development",
                            LaboratoryName = "CPE Programming Lab 2",
                            RoomNo = "G-602",
                            TeacherId = new Guid("00000000-0000-0000-0000-000000001002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000103"),
                            CreateBy = "SYSTEM",
                            Description = "Networking, routing, and server configuration",
                            LaboratoryName = "CPE Network Lab",
                            RoomNo = "G-603",
                            TeacherId = new Guid("00000000-0000-0000-0000-000000001003")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000104"),
                            CreateBy = "SYSTEM",
                            Description = "Microcontroller and IoT experiments",
                            LaboratoryName = "CPE Embedded Systems Lab",
                            RoomNo = "G-604",
                            TeacherId = new Guid("00000000-0000-0000-0000-000000001004")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000105"),
                            CreateBy = "SYSTEM",
                            Description = "Digital logic and circuit practice",
                            LaboratoryName = "CPE Hardware Lab",
                            RoomNo = "G-605",
                            TeacherId = new Guid("00000000-0000-0000-0000-000000001005")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000106"),
                            CreateBy = "SYSTEM",
                            Description = "CPU and low-level system study",
                            LaboratoryName = "CPE Computer Architecture Lab",
                            RoomNo = "G-606",
                            TeacherId = new Guid("00000000-0000-0000-0000-000000001006")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000107"),
                            CreateBy = "SYSTEM",
                            Description = "Workspace for final year projects",
                            LaboratoryName = "CPE Senior Project Lab",
                            RoomNo = "G-607",
                            TeacherId = new Guid("00000000-0000-0000-0000-000000001007")
                        });
                });

            modelBuilder.Entity("Shared.Outbox.Model.Outbox", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("SYSTEM");

                    b.Property<DateTime?>("CreateOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<char>("Status")
                        .HasColumnType("character(1)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", "asset");
                });

            modelBuilder.Entity("Asset.Assets.Model.Asset", b =>
                {
                    b.HasOne("Asset.Assets.Model.Laboratory", "Laboratory")
                        .WithMany()
                        .HasForeignKey("LaboratoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Laboratory");
                });

            modelBuilder.Entity("Asset.Assets.Model.AssetUnit", b =>
                {
                    b.HasOne("Asset.Assets.Model.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsMany("Asset.Assets.ValueObject.AssetHistory", "Histories", b1 =>
                        {
                            b1.Property<Guid>("AssetUnitId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("ActionType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<DateTime?>("ApprovedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid?>("ApprovedBy")
                                .HasColumnType("uuid");

                            b1.Property<string>("FromAvailabilityStatus")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("FromOperationalStatus")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<Guid?>("FromOwnerId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("PerformedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("PerformedBy")
                                .HasColumnType("uuid");

                            b1.Property<string>("ReferenceNo")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Remark")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<string>("ToAvailabilityStatus")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("ToOperationalStatus")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<Guid?>("ToOwnerId")
                                .HasColumnType("uuid");

                            b1.HasKey("AssetUnitId", "Id");

                            b1.ToTable("AssetUnitHistories", "asset");

                            b1.WithOwner()
                                .HasForeignKey("AssetUnitId");
                        });

                    b.Navigation("Asset");

                    b.Navigation("Histories");
                });

            modelBuilder.Entity("Asset.Assets.Model.AssetUnitCondition", b =>
                {
                    b.HasOne("Asset.Assets.Model.AssetUnit", "AssetUnit")
                        .WithOne("Condition")
                        .HasForeignKey("Asset.Assets.Model.AssetUnitCondition", "AssetUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetUnit");
                });

            modelBuilder.Entity("Asset.Assets.Model.AssetUnitImage", b =>
                {
                    b.HasOne("Asset.Assets.Model.AssetUnit", "AssetUnit")
                        .WithMany("Images")
                        .HasForeignKey("AssetUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetUnit");
                });

            modelBuilder.Entity("Asset.Assets.Model.AssetUnit", b =>
                {
                    b.Navigation("Condition");

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
